### ISSUE TITLE
ImportDict() forgetting OrderedDict order

### ISSUE THREAD

**Issue by interrogator** [dmnfarrell/tkintertable#16]
Hey, thanks for the great tool!

My problem is a small one: if I pass `ImportDict()` a (sorted) `OrderedDict()` object, this order is not remembered when I load up the 'spreadsheet'.

I was thinking, perhaps wherever this sorting happens in the code, it'd be possible to just typecheck the dict object that's being passed in. If it's `dict`, do as normal. If it's an `OrderedDict`, the user must already have the proper order determined, so it could be left unsorted.

Cheers!

**Comment by interrogator** [comment]
Just in case anybody needs it, my current workaround, which is very ugly, is to:

1. Add a row to my data with indexes as `indexes` (in Pandas, so `df.ix['indexes'] = df.sum()`

Then, after loading it in:

2. Sort: `table.sortTable(columnName = 'indexes')`
3. Get index of this column: `i = model.columnNames.index('indexes')`
4. Delete it: `model.deleteColumn(i)`

@dmnfarrell I'm sure this isn't the best way!

**Comment by dmnfarrell** [comment]
Yes a typecheck for orderedict is probably best. If you are using pandas dataframes you might want to switch to [pandastable](https://github.com/dmnfarrell/pandastable) which is a new version of this library for python3 and uses dataframes directly.
