### ISSUE TITLE
Column type

### ISSUE THREAD

**Issue by Adviser-ua** [dmnfarrell/tkintertable#18]
Hello! I would like to add column with type DropDownList. Tell me please where it I can add in your code ?

**Comment by dmnfarrell** [comment]
Hi. To add that you would have to implement it in `Tables.py`. `drawCellEntry` is where the entry window is created when the user wants to edit a cell. So you would have to add code to create the drop down list instead of a text entry frame.

**Comment by Adviser-ua** [comment]
thank you for fast response, it is will help me ) tkintertable is very functional tool. respect!
