### ISSUE TITLE
TypeError: tuple indices must be integers, not dict

### ISSUE THREAD

**Issue by mbolder** [dmnfarrell/tkintertable#20]
Hi, Tkintertable looks like a great tool, but i seem to have a problem importing a dict from mysql.
After fetching it from mysql, my dict (ret2) looks like this:

print(ret2) 
({'Kundenkonto': 10000L, 'BUKey': 3L, 'Umsatz': 99.99, 'Sachkonto': 8400L, 'Kundenname': 'TEST', 'UstID': '', 'Rechnungsdatum': None, 'Belegtext': 'Rakuten Bestell-Nr.: 111-222-333', 'PDF': None, 'Belegfeld2': '0', 'MwSt': 19L, 'Waehrung': 'EUR', 'Rechnungsnummer': 'RE1000'}, and so on

model = table.model
model.importDict(ret2)
table.redrawTable()

TypeError: tuple indices must be integers, not dict

What am I missing?

Thank you

**Comment by dmnfarrell** [comment]
Are you sure it's a dict. What you printed looks like a tuple that contains a dict. the error also indicates this. The importDict method isn't that flexible.
