### ISSUE TITLE
Callback function on delete row.

### ISSUE THREAD

**Issue by SilvioMessi** [dmnfarrell/tkintertable#23]
Hi,
how can i execute my own custom function when a row is deleted?

**Comment by dmnfarrell** [comment]
The best way would be to create a new Table class that inherits from TableCanvas and then just add to this a new deleteRow method that contains your new code. Everything else should behave the same. 

something like this:
```
class MyTable (TableCanvas):
    def __init__(self, parent=None, model=None, width=None, height=None,
                     rows=10, cols=5, **kwargs):
        TableCanvas.__init__(self, parent, bg='white',
                         width=width, height=height)
    def deleteRows(self):
        #do stuff

```

**Comment by SilvioMessi** [comment]
Perfect! Exactly what i wanted!
Thank you.
