### ISSUE TITLE
how to import data from a text file by the function?

### ISSUE THREAD

**Issue by autodataming** [dmnfarrell/tkintertable#24]
'''
Importing from a text file can be down interactively from the GUI by right clicking on the table and choosing 'Import Table' from the popup menu.
'''
By right click the gui,we can import data from text file.

Can I import data from a text file by the function?

**Comment by dmnfarrell** [comment]
This doesn't seem to be implemented without the dialog appearing which is stupid. Some of this code is pretty ropey. Just create a function that imports the file into a dict then creates the model and passes it to a table (or updates a table with the model):

```
def importcsv(filename,sep=','):
    import csv
    dictreader = csv.DictReader(open(filename, "rb"), delimiter=sep)
    dictdata = {}
    count=0
    for rec in dictreader:
        dictdata[count]=rec
        count=count+1
    return dictdata

d = importcsv('ff.csv')
model.importDict(d)
table=TableCanvas(model=model)
```

**Comment by dmnfarrell** [comment]
You can now import directly into the table from a file:
```
table.importCSV('ff.csv',sep=',')
table.redraw()
```
