### ISSUE TITLE
how to initial a table by a function 

### ISSUE THREAD

**Issue by autodataming** [dmnfarrell/tkintertable#25]
how to initial a special size table by a function ? for example ,I would like to design 4*10 table,all grids in table are empty.

**Comment by dmnfarrell** [comment]
There are rows and cols arguments in the constructor of the TableCanvas class. See http://pythonhosted.org/tkintertable/

e.g.

table = TableCanvas(parent, rows=4, cols=10)

**Comment by autodataming** [comment]
thank you very much.
