### ISSUE TITLE
reload tkintertable from csv

### ISSUE THREAD

**Issue by stevanusadi** [dmnfarrell/tkintertable#27]
hi, good morning...
I am trying to build a table from csv file, and it worked at the first load.
The problem is when the csv file is changed, I want the table is redraw with the new data, But its not change at all... 
how do I redraw the table?  i use table.redrawTable() but its not working... 
thankyou

**Comment by dmnfarrell** [comment]
You'd have to show me the code you're using.

**Comment by stevanusadi** [comment]
HI,
I have a csv file, that came from database. this csv file is created from another python script that triggered when this python got notify from postgresql and it will be changes everytime this another python script is fired up.
the csv file : 
[query.txt](https://github.com/dmnfarrell/tkintertable/files/1100353/query.txt)

and this is my script that trying to show this csv : 

`import sys
import Tkinter as tk
from PIL import Image, ImageTk
import time
from tkintertable.Tables import TableCanvas
from tkintertable.TableModels import TableModel
import csv

def importcsv(filename, sep=','):
    dictreader = csv.DictReader(open(filename, 'rb'), delimiter=sep)
    dictdata = {}
    count = 0
    for rec in dictreader:
        dictdata[count]=rec
        count=count+1
    return dictdata

class App:
    def __init__(self, master):
        self.master = master
        self.screenSizeX = self.master.winfo_screenwidth()                 
        self.screenSizeY = self.master.winfo_screenheight()               
        self.frameSizeX  = int(self.screenSizeX )
        self.frameSizeY  = int(self.screenSizeY )
        self.framePosX   = (self.screenSizeX - self.frameSizeX)/2          
        self.framePosY   = (self.screenSizeY - self.frameSizeY)/2          
        self.master.geometry('%sx%s+%s+%s'%(self.frameSizeX, self.frameSizeY, self.framePosX,    self.framePosY)) 
        self.drawFrame()
        self.drawTable()
        
    def drawFrame(self):
        self.mainFrame = tk.Frame(self.master, height = self.screenSizeY, width = self.screenSizeX, bg = 'light green')
        self.mainFrame.pack(padx = 10, pady = 10)
        
        self.titleFrame = tk.Frame(self.mainFrame, height = 0.4*self.screenSizeY , width = self.screenSizeX , bg = 'light green')
        self.titleFrame.pack(padx = 10, pady = 0, side = tk.TOP)
        self.middleFrame = tk.Frame(self.mainFrame, height = 0.6*self.screenSizeY, width = self.screenSizeX, bg = 'green')
        self.middleFrame.pack(padx = 10, pady = 0)
        self.bottomFrame = tk.Frame(self.mainFrame, height = 0.1*self.screenSizeY , width = self.screenSizeX, bg = 'light green')
        self.bottomFrame.pack(padx = 10, pady = 0, side = tk.BOTTOM )

        self.mainTitle = tk.Label(self.titleFrame, text = 'bla bla bla', font = ('Helvetica', 32, 'bold'), fg='White', bg="light green")
        self.mainTitle.pack()
        self.bottomTitle = tk.Label(self.bottomFrame, text = 'bla bla bla', font = ('Helvetica', 24, 'bold'), fg='White', bg="light green")
        self.bottomTitle.grid(row=0, column=0)
                
    def drawTable(self):
        self.d = importcsv('query.csv')
        self.model = TableModel()
        self.table = TableCanvas(self.middleFrame, model=self.model, width = self.screenSizeX, thefont = ('Arial', 17),
                            height = 0.7*self.screenSizeY, rowheaderwidth=0, showkeynamesinheader=True ,rowheight=50, editable=False,
                              rowselectedcolor='White')
        
        self.model.importDict(self.d)
        
        self.model.columnwidths['0'] = 0
        self.model.columnwidths['1'] = 0.15*self.frameSizeX
        self.model.columnwidths['2'] = 0.15*self.frameSizeX 
        self.model.columnwidths['3'] = 0
        self.model.columnwidths['4'] = 0.52*self.frameSizeX
        self.model.columnwidths['5'] = 0
        self.model.columnwidths['6'] = 0.15*self.frameSizeX

        self.model.columnlabels['0'] = 'NO'
        self.model.columnlabels['1'] = 'KELAS'
        self.model.columnlabels['2'] = 'KAPASITAS'
        self.model.columnlabels['3'] = 'CADANGAN'
        self.model.columnlabels['4'] = 'KETERANGAN'
        self.model.columnlabels['5'] = 'TERISI'
        self.model.columnlabels['6'] = 'TERSEDIA'
        
        self.model.moveColumn(self.model.getColumnIndex('0'),0)
        self.model.moveColumn(self.model.getColumnIndex('1'),1)
        self.model.moveColumn(self.model.getColumnIndex('2'),2)
        self.model.moveColumn(self.model.getColumnIndex('3'),4)
        self.model.moveColumn(self.model.getColumnIndex('4'),6)
        self.model.moveColumn(self.model.getColumnIndex('5'),5)
        self.model.moveColumn(self.model.getColumnIndex('6'),3)

        self.model.setSortOrder(0)
        self.table.createTableFrame()
        #self.table.redrawTable()    
          
def main(): 
    root = tk.Tk()
    app = App(root)
    root.mainloop()
    
if __name__ == '__main__':
    main()`

how do i refresh this table cell that came from csv file, when this csv file is modified?
i am trying  to redrawTable but its not working..
thanks in advance.

#ps, I am a new in python...

**Comment by dmnfarrell** [comment]
I couldn't get this working without making some changes to syntax problems. Also a lot of the stuff you are doing with column sizes and labels is may be unnecessary. You can set the column order by using 

```self.table.model.columnNames = listofnames```

The table won't refresh when the csv file is changed as it is not linked to it. Once you import to a dict, then it's new data not connected to the csv. You would have to have a method checking the contents of the csv and re-importing and refreshing the table each time.

```
import sys,os
import Tkinter as tk
from PIL import Image#, ImageTk
import time
from tkintertable.Tables import TableCanvas
from tkintertable.TableModels import TableModel
import csv

def importcsv(filename, sep=','):
    dictreader = csv.DictReader(open(filename, 'rb'), delimiter=sep)
    dictdata = {}
    count = 0
    for rec in dictreader:
        dictdata[count]=rec
        count=count+1
    return dictdata

class App(tk.Frame):
    def __init__(self):
        tk.Frame.__init__(self)
        #self.master = master
        self.screenSizeX = self.master.winfo_screenwidth()
        self.screenSizeY = self.master.winfo_screenheight()
        self.frameSizeX = int(self.screenSizeX )
        self.frameSizeY = int(self.screenSizeY )
        self.framePosX = (self.screenSizeX - self.frameSizeX)/2
        self.framePosY = (self.screenSizeY - self.frameSizeY)/2
        self.master.geometry('%sx%s+%s+%s'%(self.frameSizeX, self.frameSizeY, self.framePosX, self.framePosY))
        self.drawFrame()
        self.drawTable()

    def drawFrame(self):
        self.mainFrame = tk.Frame(self.master, height = self.screenSizeY, width = self.screenSizeX, bg = 'light green')
        self.mainFrame.pack(padx = 10, pady = 10)

        self.titleFrame = tk.Frame(self.mainFrame, height = 0.4*self.screenSizeY , width = self.screenSizeX , bg = 'light green')
        self.titleFrame.pack(padx = 10, pady = 0, side = tk.TOP)
        self.middleFrame = tk.Frame(self.mainFrame, height = 0.6*self.screenSizeY, width = self.screenSizeX, bg = 'green')
        self.middleFrame.pack(padx = 10, pady = 0)
        self.bottomFrame = tk.Frame(self.mainFrame, height = 0.1*self.screenSizeY , width = self.screenSizeX, bg = 'light green')
        self.bottomFrame.pack(padx = 10, pady = 0, side = tk.BOTTOM )

        self.mainTitle = tk.Label(self.titleFrame, text = 'bla bla bla', font = ('Helvetica', 32, 'bold'), fg='White', bg="light green")
        self.mainTitle.pack()
        self.bottomTitle = tk.Label(self.bottomFrame, text = 'bla bla bla', font = ('Helvetica', 24, 'bold'), fg='White', bg="light green")
        self.bottomTitle.grid(row=0, column=0)

    def drawTable(self):
        self.d = importcsv('query.csv')
        print self.d
        self.model = TableModel()
        self.table = TableCanvas(self.middleFrame, model=self.model, width = self.screenSizeX, thefont = ('Arial', 17),
                            height = 0.7*self.screenSizeY, rowheaderwidth=0, showkeynamesinheader=True ,rowheight=50, editable=False,
                              rowselectedcolor='White')

        self.model.importDict(self.d)

        self.model.setSortOrder(0)
        self.table.createTableFrame()
        self.table.autoResizeColumns()
        #self.table.model.columnNames = ['name','age']
        self.table.redrawTable()


def main():
    app = App()
    app.mainloop()

if __name__ == '__main__':
    main()
```

**Comment by stevanusadi** [comment]
HI, it's me again...
I want to say thank you Sir, @dmnfarrell 
after i have changed a few of my code, now everything is working perfectly like a charm.
thanks for your guiding...
thanks in advance
regards,

sikil.walang

**Comment by dmnfarrell** [comment]
No problem. I'll close this issue.
