### ISSUE TITLE
tkintertable error when creates .EXE file with cx_Freeze

### ISSUE THREAD

**Issue by kmiloarguello** [dmnfarrell/tkintertable#28]
Hi everyone, 

I have found a bug when I try to create cx_freeze .exe file.
For example, I have 2 files: `app.py` and `setup.py`

Inside of app.py

```
from Tkinter import *
from tkFileDialog import askopenfilename
from tkintertable.Tables import TableCanvas
from tkintertable.TableModels import TableModel
.
.
.

window = Tk()

window.mainloop()

```
When I compile this using python it runs perfectly.
Notice that I have only called the library and I am not using it.
Now I want to create an `.EXE` file using cx_Freeze.

```
from cx_Freeze import setup,Executable

includes = []
excludes = []
packages = []
filename = "app.py"

exe = Executable(
   script = "app.py",
   base = 'Win32GUI',
   targetName = "app.exe",
   icon = 'icon.ico'
)

setup(
    name = 'App',
    version = '0.1',
    description = 'App description',
    author = 'author',
    author_email = 'mail@mail.com',
    options = {'build_exe': {'excludes':excludes,'packages':packages,'includes':includes}},
    executables = [exe])

```

The error occurs when I open the `.exe` file. This happens: 

![capture](https://user-images.githubusercontent.com/13356409/31829876-308fe00a-b584-11e7-86a8-8c1f820ca50c.PNG)

There are an error with PMW loader. 

I really dont know what I have to do. Is it PMW error? or is a tkintertable bug?

Thanks.

**Comment by dmnfarrell** [comment]
It could be the version of Pmw you are using. Maybe try an older one. It's been a long time since I used this. I no longer actively update this code. 
Is there any particular reason why you need to freeze this libary. Do you want to use the application? I usually recommend people move to pandastable instead since I still update that and its far more advanced.

**Comment by kmiloarguello** [comment]
I fixed that, modifying PMW library where the error occurred. Yes, I want to use for my tkinter application. The next application I will use Pandastable. Thank you
