### ISSUE TITLE
not python 3.x friendly but still installable via pip

### ISSUE THREAD

**Issue by pavlix** [dmnfarrell/tkintertable#33]
Apparently not Python 3.x ready but probably something wrong with the metadata as it installs for Python 3.x using pip from the cheese shop.

```
Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkintertable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pavlix/.local/lib/python3.6/site-packages/tkintertable/__init__.py", line 24, in <module>
    from Tables import *
ModuleNotFoundError: No module named 'Tables'

```

**Comment by dmnfarrell** [comment]
setup.py has been changed to reflect this. unfortunately it seems you can no longer update metadata on pypi without making a new release.

**Comment by pytesnim** [comment]
Hello,
I am having the same problem, any solution to this? Is it not compatible with Python 3.6?

**Comment by pytesnim** [comment]
Thanks!

**Comment by dmnfarrell** [comment]
I'd have to do some rewriting to make it python 3 compatible. Normally I refer people to pandastable which is kept up to date and has many more features. If there's some reason you really want to use this one I can update it for python 3.

**Comment by dmnfarrell** [comment]
@pavlix This is now python 3 compatible. Will be released on pip soon.

**Comment by Plancalkuele** [comment]
When will it be released on pip? I'm still having this problem.

**Comment by dmnfarrell** [comment]
@Plancalkuele What problem. It was updated for python 3 since version 1.3

**Comment by Plancalkuele** [comment]
When I run the example code from https://github.com/dmnfarrell/tkintertable/wiki/Example-Code

I receive:
`from tkintertable import TableCanvas, TableModel ImportError: cannot import name 'TableCanvas'`

The example code from tkpandastable works. (https://github.com/dmnfarrell/pandastable/wiki/Code-Examples)

The requirements are satisfied after installing tkintertable:
`Requirement already satisfied: tkintertable in ~/miniconda3/envs/../lib/python3.6/site-packages (1.3.1)`

**Comment by dmnfarrell** [comment]
I am not sure I understand the reference to pandastable. pandastable is a completely separate package. If you prefer just use that instead.
This error implies that the package is not in your site-packages. If you are still getting this error maybe re-install?
I will push version 1.3.2 shortly which has some bug fixes for python 3, but if you see any others let me know.

**Comment by Plancalkuele** [comment]
I referenced pandastable because you referenced pandastable yourself in a previous message on this issue. I just tested the example for both packages but would rather like to use tkintertable first for a project I'm working on.

Anyway, I checked of course the site-packages folder and as stated before tkintertable has been installed by pip in the right folder. I just uninstalled and reinstalled tkintertable.
Same error:
`ImportError: cannot import name 'TableCanvas'`

Very confusing because I can see the class is there when taking a look in Tables.py

**Comment by dmnfarrell** [comment]
The import problem would happen if the site-packages folder is not in your PYTHONPATH. I am not that familiar with anaconda but it should just work.
Did you try opening a python interpreter in a console and importing the class to test?

**Comment by Plancalkuele** [comment]
Alright, problem fixed. Kind of embarrassing but I named the python script the same as the package. That's why it didn't find the class of course. Sorry for wasting your time. The package works fine with miniconda.

**Comment by dmnfarrell** [comment]
No problem, it's happened to me too.
