### ISSUE TITLE
rows and columns of tablemodel imported from a dictionary are not ordered 

### ISSUE THREAD

**Issue by fanner01** [dmnfarrell/tkintertable#34]
because the items in python dictionary are not ordered in the order that they're inserted, the rows and columns are not ordered if tablemodel with dictionary is used. the author may consider use an advanced dictionary data structure.

**Comment by fanner01** [comment]
i just checked that it is solved in python 3.7

Changed in version 3.7: Dictionary order is guaranteed to be insertion order. This behavior was implementation detail of CPython from 3.6.

**Comment by dmnfarrell** [comment]
I will shortly add python 3 support so it should work then. Thanks.
