### ISSUE TITLE
Initialize TableClass with Data

### ISSUE THREAD

**Issue by misimpso** [dmnfarrell/tkintertable#35]
Hi,

I've just found this and it is really well done! I am confused on how to intialize the TableCanvas object with data. I saw the part in the README for [updating](https://github.com/dmnfarrell/tkintertable#get-data-into-the-table), but either I am not understanding it right or when I do it as shown in the section it appends my data to the end of the existing model in the object. I want to replace the data in the sheet with my new model so the next logical step would be to pass it in with the TableClass object creation, but I am not sure of the required data structure for the class to utilize the data fully. 

Could you outline the base data structure for passing in data into the TableCanvas constructor?

**Comment by dmnfarrell** [comment]
You can use the importDict method to get that data into the table.
I only really do essential bug fixes on this library now but I am updating it to be python 3 compatible. So have added a data keyword to the constructor of the TableCanvas that you can pass this dict in directly. You can refer to the updated readme page.
