### ISSUE TITLE
When I run the sample code python 3 

### ISSUE THREAD

**Issue by JoseBaena** [dmnfarrell/tkintertable#36]
Hi,
when I run the sample code in Python 3, I got  this error message. 

    ostyp = string.lower(os.environ[var])

AttributeError: module 'string' has no attribute 'lower'

from tkintertable import TableCanvas, TableModel
from tkinter import *
import random
from collections import OrderedDict

data = {'rec1': {'col1': 99.88, 'col2': 108.79, 'label': 'rec1'},
        'rec2': {'col1': 99.88, 'col2': 321.79, 'label': 'rec3'},
        'rec3': {'col1': 29.88, 'col2': 408.79, 'label': 'rec2'}
        }

from tkintertable.Testing import sampledata
data=sampledata()
#print(data)

class TestApp(Frame):
    """Basic test frame for the table"""

    def __init__(self, parent=None):
        self.parent = parent
        Frame.__init__(self)
        self.main = self.master
        self.main.geometry('800x500+200+100')
        self.main.title('Test')
        f = Frame(self.main)
        f.pack(fill=BOTH,expand=1)
        table = TableCanvas(f, data=data)
        table.importCSV('test.csv')
        print (table.model.columnNames)
        #table.model.data[1]['a'] = 'XX'
        #table.model.setValueAt('YY',0,2)
        table.show()
        return

app=TestApp()
app.mainloop()

**Comment by dmnfarrell** [comment]
What operating system.

**Comment by JoseBaena** [comment]
Windows 10 version 1803. 

I am using Spyder-Anaconda

**Comment by dmnfarrell** [comment]
this should be fixed on git

**Comment by JoseBaena** [comment]
Now I got this error message 


File "C:\Users\Jose\AppData\Local\Continuum\anaconda3\lib\site-packages\tkintertable\Tables.py", line 2027, in loadPrefs
    if not prop in self.prefs.prefs:

AttributeError: 'Preferences' object has no attribute 'prefs'

**Comment by dmnfarrell** [comment]
I can't replicate that error. You could remove the file .Table_preferences in home folder if it's there and run again. Are you running that code from within spyder?

**Comment by JoseBaena** [comment]
It isn't in home folder. Yes, I am running within spyder.

**Comment by dmnfarrell** [comment]
Try running the test app outside spyder first. Normally it should generate a prefs file in your home dir.

**Comment by JoseBaena** [comment]
I was looking at the wrong folder. I removed the .Table_preferences in home folder and then it Worked. Thank you so much.
