### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by lanpirot** [dmnfarrell/tkintertable#37]
Would it be possible to implement the following?
I would like to use the tkintertable in a read only mode, where users can only scroll through the table (and highlight a row).
For this right-clicking the table should have no effect. Left clicking on the scrollbar works as expected. Left clicking the table has no effect or only highlights the clicked row.

**Comment by dmnfarrell** [comment]
Yes this is trivial. You can now pass read_only to the constructor to have this behaviour. Or set ```table.read_only=True```

**Comment by lanpirot** [comment]
You are great! :1st_place_medal:
