### ISSUE TITLE
PyPi different version

### ISSUE THREAD

**Issue by SilentPony** [dmnfarrell/tkintertable#42]
PyPi in its 1.3.1 version of tkintertable has a '1.2' version shown (it is also marked as 1.2 in `__init__.py`).

Also, the 1.3.1 seems not fully compatible with the python 3 since it still has the string.lower() calls.

**Comment by dmnfarrell** [comment]
Which string.lower() calls are remaining.

**Comment by SilentPony** [comment]
In file [Tables.py, line 2243](https://github.com/dmnfarrell/tkintertable/blob/f31f648449a29702f22ea2ab822248cbacc2c10c/tkintertable/Tables.py#L2243), it's in the 1.3.1 tagged commit.

**Comment by dmnfarrell** [comment]
ok thanks
