### ISSUE TITLE
setcellColor(row,col,color) doesn't work 

### ISSUE THREAD

**Issue by vnahmias** [dmnfarrell/tkintertable#43]
Hello I have intern issues when calling the method setCellColor(row,col,color) it triggers the following error : 

`NameError: name 'IntType' is not defined`

It seems that it is because of python 3.6 and we use `Int` instead of `IntType`.  However after having modified this line i had the following error : `NameError: name 'Int' is not defined` so i assume that i guessed Wrong.

Here is your function : 
```
1180    def setcellColor(self, rows, cols=None, newColor=None, key=None, redraw=True): 
1181          """Set the cell color for one or more cells and save it in the model color""" 
1182   
1183          model = self.getModel() 
1184          if newColor == None: 
1185              import tkColorChooser 
1186              ctuple, newColor = tkColorChooser.askcolor(title='pick a color') 
1187              if newColor == None: 
1188                  return 
1189   
1190          if type(rows) is IntType: 
1191              x=rows 
1192              rows=[] 
1193              rows.append(x) 
1194          if self.allrows == True: 
1195              #we use all rows if the whole column has been selected 
1196              rows = range(0,self.rows) 
1197          if cols == None: 
1198              cols = range(self.cols) 
1199          for col in cols: 
1200              for row in rows: 
1201                  #absrow = self.get_AbsoluteRow(row) 
1202                  model.setColorAt(row, col, color=newColor, key=key) 
1203                  #setcolor(absrow, col) 
1204          if redraw == True: 
1205              self.redrawTable() 
1206          return 
```

I chose to delete the if Statement line 1190 in order to skip this verification knowing that when i am calling the function i give an Int for row and col attributes.

But i had an other error : 

`for col in cols:
TypeError: 'int' object is not iterable `

This function seems totally broken man

**Comment by dmnfarrell** [comment]
Are you passing cols as an int when you call the function? 
cols should be a list.
I can fix the IntType issue. There are bound to be python 3 bugs since I converted it. If you see an others let me know.

**Comment by dmnfarrell** [comment]
The int type bug is fixed.
