### ISSUE TITLE
unable to make a cell Readonly 

### ISSUE THREAD

**Issue by DEEP7696** [dmnfarrell/tkintertable#45]
unable to make a cell Readonly

**Comment by sathannan** [comment]
I have proposed for a file change which should fix that issue. After it has been accepted, you would be able to do: TableCanvas(self.tframe,read_only=True) and the entire table will become read-only.

**Comment by dmnfarrell** [comment]
ok done. thanks

**Comment by DEEP7696** [comment]
Thanks Dmnfarrell, but i need to make some particular cells read only.
Kindly reply if it is possible.
I would be very grateful.

Thanks

**Comment by dmnfarrell** [comment]
You can't make individual cells read only I'm afraid. If you know enough python you could add that functionality yourself probably.

**Comment by DEEP7696** [comment]
Thanks for reply.
I have already figured it out by doing some changes in the module.
