### ISSUE TITLE
Python3: Errors

### ISSUE THREAD

**Issue by AokiAhishatsu** [dmnfarrell/tkintertable#48]
```
C:\Users\kig0pkt12\AppData\Local\Programs\Python\Python37\python.exe C:/Code/test_project/test.py
Traceback (most recent call last):
  File "C:/Code/LeM_Test/P208_ASU_GUI/test.py", line 12, in <module>
    rowselectedcolor='yellow',reverseorder=1)
  File "C:\Users\kig0pkt12\AppData\Local\Programs\Python\Python37\lib\site-packages\tkintertable\Tables.py", line 60, in __init__
    self.ostyp = self.checkOSType()
  File "C:\Users\kig0pkt12\AppData\Local\Programs\Python\Python37\lib\site-packages\tkintertable\Tables.py", line 2243, in checkOSType
    ostyp = string.lower(os.environ[var])
AttributeError: module 'string' has no attribute 'lower'
```

**Comment by AokiAhishatsu** [comment]
Already fixed in master - please release/update to PyPI

**Comment by dmnfarrell** [comment]
Will do that shortly. Any other bugs related to python 3 that you have seen please report.

**Comment by AokiAhishatsu** [comment]
Current master, simple Table with read_only=True in constructor

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\kig0pkt12\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\code\tkintertable\tkintertable\Tables.py", line 915, in handle_left_click
    if self.read_only is True:
AttributeError: 'TableCanvas' object has no attribute 'read_only'
```

**Comment by AokiAhishatsu** [comment]
I can still edit column header name despite `read_only=True`.
How can I disable right/context-menu completely?

**Comment by dmnfarrell** [comment]
this should be fixed now

**Comment by dmnfarrell** [comment]
1.3.2 is now released.

**Comment by SchuppiM** [comment]
Hi all
I’m also getting this error using a tkintertable widget: 
AttributeError: 'TableCanvas' object has no attribute 'read_only'
It happens when I’m click in the table to position my cursor in a cell.
Now you are writing there is a solution on this.
Where can I get the solution?
Being very new to Python, it is a bit confusing!
Thx a ton for your help!
Cheers
Michael

**Comment by dmnfarrell** [comment]
@SchuppiM 
Is your version up to date?

**Comment by SchuppiM** [comment]
@dmnfarrell
My tkinter version? I downloaded beginning of March. (very new to Python)
I have Python Version 37-32.
Can I check my tkinter Version?

**Comment by dmnfarrell** [comment]
how did you install tkintertable

**Comment by SchuppiM** [comment]
@dmnfarrell
I downloaded it from... I think here...
Version 1.3, at least this is what it says in the CHANGES file.
Run the Setup.py

**Comment by dmnfarrell** [comment]
You can try install the latest version and see if that fixes it. latest is 1.3.2

**Comment by SchuppiM** [comment]
@dmnfarrell
Do you have a link please? So I get the latest Version.
Can I simply replace the *.py I have installed or is it better to run the Setup?

**Comment by dmnfarrell** [comment]
Jus download the zip and run setup.py like you did before. 
https://github.com/dmnfarrell/tkintertable/archive/master.zip

**Comment by SchuppiM** [comment]
@dmnfarrell
Gr8! Thx a ton!

**Comment by SchuppiM** [comment]
@dmnfarrell
Ok, gr8! The error is gone! Thx so much!
Now I have an other proble where I thought it is because of the error.
When I click in my table, it is not activation the row I clicked.
I have this statement
self.UsersWOTable.bind("<ButtonRelease-1>", self.ClickinTableEvent)
that jumpes in to self.ClickinTableEvent and does there what it should do with the active row, but it should first activate the row I clicked....
Any idea?

**Comment by SchuppiM** [comment]
oh, the values of self.UsersWOTable.getSelectedRow() and self.UsersWOTable.getSelectedColumn() are always those of the possition of the active row/column. Not the one I clicke latest.

**Comment by SchuppiM** [comment]
@dmnfarrell
Hmmm, ok.... can I get the values of the row, col or cell I clicked last?

**Comment by SchuppiM** [comment]
ok, Forget it, I found it.
Again! Thx so much for your help!!!!!!!
