### ISSUE TITLE
Error on basic table creation (Python 3)

### ISSUE THREAD

**Issue by zbishop3455** [dmnfarrell/tkintertable#49]
ostyp = string.lower(os.environ[var])
AttributeError: module 'string' has no attribute 'lower'

        self.top = Toplevel(master)

        self.rows = len(pickers)

        data = {'rec1': {'col1': 99.88, 'col2': 108.79, 'label': 'rec1'},
                'rec2': {'col1': 99.88, 'col2': 108.79, 'label': 'rec2'}}

        self.table = TableCanvas(self.top, data=data, rows=self.rows, columns=3)
        self.table.show()
        self.table.redraw()

**Comment by dmnfarrell** [comment]
this is already fixed, i just need to update pip soon.
