### ISSUE TITLE
tkinertable question

### ISSUE THREAD

**Issue by SchuppiM** [dmnfarrell/tkintertable#51]
Hi
I'm using tkinertable and want to change the text in a cell, or better the whole row to bold.
Couldn't find anything in the web.
How can I do this?
Thx for your support!

**Comment by dmnfarrell** [comment]
Entering text should be easy unless there is something wrong with the table. You cannot format individual rows. What are u using this table for?

**Comment by SchuppiM** [comment]
@dmnfarrell  
Filling the table is no issue.
I'm filling data from a DB. One row are ammounts. I added them up and wanted to have the total row in bold. As e.g. in an Excel.

**Comment by dmnfarrell** [comment]
Sorry I misread. Yes you can't format by row. If you want more advanced features you could try pandastable perhaps.

**Comment by SchuppiM** [comment]
@dmnfarrell
No issue. Sorry to answer this late…. Easter weekend,
Ok, no problem, it will be ok like this.
I thought it’s possible to change this in individual cells as it is possible to change the colors of cells.
Might be an idea for one of the next versions 😉?

**Comment by dmnfarrell** [comment]
Thanks. I don't actively add new features to this any more. I update pandastable though and it supports row formatting.
