### ISSUE TITLE
tkintertable titlerows=

### ISSUE THREAD

**Issue by SchuppiM** [dmnfarrell/tkintertable#54]
Working with Python 3.7 using tkintertable I fount that titlerows= has no effect.
There is always one, despite of the figure I give.
Since titlerows= is not producing an error, I thought it should work.

**Comment by dmnfarrell** [comment]
Where did you get the titlerows parameter from?

**Comment by SchuppiM** [comment]
@dmnfarrell 
Searching for an option to have two column header rows (or two lines in one header row 😊) I came across it in tktable and gave it a shot, thinking it all bases on tkinter so why not. It didn’t produce an error, but also didn’t work….. ☹.
Is there a possibility to have a column header on two lines? At the moment I’m working with \n, it places the text on two lines, but the column header is not adjusting, so it looks crappy now.
Thx for your help.

**Comment by SchuppiM** [comment]
Thx for your answer and explanation.
I’m just in Phyton for a bit more than 2 months, so very fare from writing this myself.
But I think it’ll have to do as it is.
I may give it a try when I’m more experienced.
