### ISSUE TITLE
Set column header color?

### ISSUE THREAD

**Issue by dxiaosa** [dmnfarrell/tkintertable#61]
Thank you for the great tool. How to set or modify the column header color? It seems the row header's color can be changed, but the column header's color can not be located?

**Comment by dmnfarrell** [comment]
I think the column header color is hard coded and not labelled as a variable. Check the redraw method of the ColumnHeader class in Tables.py.

**Comment by dxiaosa** [comment]
Yes, I have checked it, and it seems not make sense. So, do you mean that the column color can not be changed?

**Comment by dmnfarrell** [comment]
You certainly can change it. I think it's the background color of the canvas.
I don't actively update this package any more except to fix bugs.

**Comment by dxiaosa** [comment]
OK, that is great. thank you.

**Comment by hannansatopay** [comment]
That should add the functionality to change the header color. 
To do that simply add the header color preference to the table canvas constructor as follows:
`TableCanvas(frame, data=data, headerbackgr='blue')`

Do test it with other methods such as saving and loading the preference files but in my opinion, it should work.
