### ISSUE TITLE
What is the top-left cell?

### ISSUE THREAD

**Issue by dxiaosa** [dmnfarrell/tkintertable#63]
Thank you for your previous help. And could you tell me what widget is the top-left cell in table which is surrounded by red circle? I don't find the concrete code descripting it? it seems no relation to the row header or column header?
![SD%D`G{55_ C3T6{4@ACA6](https://user-images.githubusercontent.com/17454419/69105742-35ffe380-0aa7-11ea-80a3-112b77845e0f.png)

**Comment by dmnfarrell** [comment]
It's just an empty space.
