### ISSUE TITLE
How to change the default cell text color?

### ISSUE THREAD

**Issue by dxiaosa** [dmnfarrell/tkintertable#64]
How to change the default cell text color? It seems that there are no definition for default text color, I have checked both the TableModels.py and Tables.py files, Just a 'setColorAt' class function. Everytime we have to select all data, and then click the "set text color" pop menu button, right? Thank you!

**Comment by hannansatopay** [comment]
@dxiaosa The text color is controlled by the `fgcolor` parameter, which in turn can be changed from the `drawText` function in the `Tables` python file.

**Comment by dxiaosa** [comment]
Yes, that is it, fgcolor can be set up by drawText function. But what is the default definition for table initialization if I want to set the text color when the table is initialized?

**Comment by dmnfarrell** [comment]
Those options are now in the constructor of the table canvas:
```
TableCanvas(parent=None, model=None, data=None, read_only=False,
                 width=None, height=None, bgcolor='#F7F7FA', fgcolor='black',
                 rows=10, cols=5)
```

You could check that this hasn't introduced any bugs.

**Comment by dxiaosa** [comment]
Ok, the master branch has implemented it, I just use the old version. Thank you, it works!
