### ISSUE TITLE
importCSV doesnt work

### ISSUE THREAD

**Issue by pgrozas** [dmnfarrell/tkintertable#75]
**Describe the bug**

importCSV doesnt work, i used the form in wiki table.importCSV(filename, sep=','), but "sep" says unexpected, even delete this appears problem with charmap. Using pandastable works flawsless but in tinkertable no.

TypeError: importCSV() got an unexpected keyword argument 'sep'
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 486: character maps to <undefined>

**To Reproduce**

**System**

windows 10

Operating system:
Python version: 3
Installation method (pip, git clone): pip

**Comment by ainoneko** [comment]
I grepped the source and found that there are different `def importCSV ...` in Tables.py and TableModels.py, so 
`table.model.importCSV(filename, sep=';')` 
should work. 
(It works for me, but it prepends the loaded data with 10 empty columns.)

**Comment by dmnfarrell** [comment]
should be fixed
