### ISSUE TITLE
sys is not defined

### ISSUE THREAD

**Issue by AndrewMarines** [dmnfarrell/tkintertable#76]
The sys library was not imported on Dialogs.py and Tables.py.
    if (sys.version_info > (3, 0)):
NameError: name 'sys' is not defined

Added `import sys` after after `from __future__ import absolute_import, division, print_function`. Now working.

**Comment by dmnfarrell** [comment]
Yes sorry have made this change now.

**Comment by KeroQuinn** [comment]
Hi, i added import sys after after from __future__ import absolute_import, division, print_function.But still doesn't worK.Do you have any ideas?

**Comment by AndrewMarines** [comment]
> Hi, i added import sys after after from __future__ import absolute_import, division, print_function.But still doesn't worK.Do you have any ideas?
> 
> 


Can you please share the error?

**Comment by KeroQuinn** [comment]
![image](https://user-images.githubusercontent.com/38945797/114170551-ab52a980-9965-11eb-9e7f-a88379127a26.png)
I changed a laptop to run this(the same code), and this question solved automatically.
The python version of the laptop that exception occurred is 3.9.4, and the python version of the "right" laptop is 3.7.5.

**Comment by dmnfarrell** [comment]
You probably had not updated tkintertable on the one that errored.

**Comment by KeroQuinn** [comment]
Thank you for your helping! :) Your code is amazing, and helped me a lot.
