### ISSUE TITLE
isLink function in Tables.py logic issue

### ISSUE THREAD

**Issue by syntux** [dmnfarrell/tkintertable#78]
**Describe the bug**

The table stops drawing cells after an error with isLink function. It will reappear after it is gone. The cell "Quantitative microbiome profiling links gut community variation to microbial load" caused me to notice this bug. The error gave "TypeError: string indices must be integers." That cell and the cells after are still there but you can't see them without hovering over. 

Here you can see it should be there but it's not drawn. 
![github1](https://user-images.githubusercontent.com/61816968/114458345-14782e00-9bad-11eb-9552-5a4a9749b321.png)

And after it's no longer visible after scrolling, the rest of the table works fine.
![github2](https://user-images.githubusercontent.com/61816968/114458397-2528a400-9bad-11eb-9583-2c51c5ed72c1.png)

The bug happens in the isLink function in the try statement. To fix this bug the if statement should be "if type(cell) is dict and 'link' in cell:" instead of "if 'link' in cell:" in Tables.py

**To Reproduce**
Steps to reproduce the behavior: Display "Quantitative microbiome profiling links gut community variation to microbial load" from inside a dictionary of dictionary.  The word link triggers this bug. The variable celltxt will become "Quantitative microbiome profiling links g" from inside the function drawText inside the statment "if self.isLink(celltxt) == True:"  and the type will be a string.

**System**

Operating system: Windows 10
Python version: 3.6.4
Installation method (pip, git clone): pip

**Comment by dmnfarrell** [comment]
Thanks. Could you submit a pull request with the fix?

**Comment by dmnfarrell** [comment]
this appears to have already been fixed. you should check the most recent code. a new release is out which should include all recent big fixes.
