### ISSUE TITLE
No support for Python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dmnfarrell/tkintertable#9]
```
There is no support for Python 3, even if

pip install tkintertable

only puts out some warnings.
Code crashes for some

print '...'

statements.

```

Original issue reported on code.google.com by `pierrepr...@gmail.com` on 18 Dec 2013 at 3:28

**Comment by dmnfarrell** [comment]
This library won't work with python 3 and isn't designed to. Python 3 users can try pandastable.
Or else fork this project and update it to 3!

**Comment by TigerDeng** [comment]
Pity that I am on Mac OS.
Thus pandastable does NOT work at all. (even for simplest demo)

having ported this into 3.  as above, but still suffers problems. 

One is --------- sight~~~~~~
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by dmnfarrell** [comment]
The user above attempted to port to python 3 but did not attempt to incorporate the code using a pull request. It is definitely possible to support python 3 but I don't have time to do it. Any effort I expend is on pandastable.
